### PR TITLE
fix: pkgRoot for release

### PR DESCRIPTION
**Pull request by marcelltoth**
Hopefully this fixes the release for once for all

### CODE REVIEW

**Comment by marcelltoth** [comment]
Does this look good to you @P0lip ?

**Comment by P0lip** [comment]
hmmm, I'm not sure whether it'll work. We can try, but I have no clue if it's allowed to place a different property next to `extends`.

**Review by P0lip — APPROVED** [review]
If it doesn't work, let's just apply the same (simple) setup I did here https://github.com/stoplightio/ordered-object-literal

**Comment by marcelltoth** [comment]
It worked 🎉 
https://www.npmjs.com/package/@stoplight/json-schema-generator

**Pull request merged**
